/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2025-07-29T00:31:16.966-03:00[America/Buenos_Aires]
 * <br>
*  The generated test suite contains 1 tests
 * <br>
*  Covered targets: 4
 * <br>
*  Used time: 0h 0m 32s
 * <br>
*  Needed budget for current results: 6%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_faults_Test {

    
    private static String baseUrlOfSut = "http://localhost:8080";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (400) POST:/api/xml/receive-xml-respond-string
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_0_postOnReceive_xml_respond_stringReturnsSchemaInvalidResponse() throws Exception {
        
        // Fault101. Received A Response From API That Is Not Valid According To Its Schema. Response status 400 not defined for path '/api/xml/receive-xml-respond-string'.
        given().accept("*/*")
                .contentType("application/xml")
                .body(<body><name>zubV7Fu5Mzj8EVW</name><age>861</age></body>)
                .post(baseUrlOfSut + "/api/xml/receive-xml-respond-string")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");
    }


}
